---
- name: "install windows vm from template"
  hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: "Create Namespace {{ namespace }}"
      kubernetes.core.k8s:
        state: present
        template: namespace.yml.j2
      
    - name: "Create VirtualMachine"
      kubernetes.core.k8s:
        state: present
        template: virtualmachine.yml.j2

    - name: Wait for VM to be ready
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      register: deploy_collection_vm
      retries: 60
      delay: 10
      until:
      - deploy_collection_vm.resources[0].status is defined
      - deploy_collection_vm.resources[0].status.ready is true

    - name: Wait for VM IP to be populated
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachineInstance
        name: "{{ name }}"
        namespace: "{{ namespace }}"
      register: deploy_collection_vmi
      retries: 60
      delay: 10
      until: (deploy_collection_vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0

    - name: "Create Service"
      kubernetes.core.k8s:
        state: present
        template: service.yml.j2

    - name: "Create Route"
      kubernetes.core.k8s:
        state: present
        template: route.yml.j2
